language: go

go:
  - 1.7
  - tip

os:
  - linux

script:
  - go test -v -race ./...

before_deploy:
  - go get github.com/mitchellh/gox
  - gox -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}" .

deploy:
  provider: releases
  api_key:
    secure: PsJBzXB0f/gKKQVlWWn50v+6BxmytaH+mNn1NKYrhciRSDzazjc8hAm/+RzAE/q2h/9N1MoL2f6Ez3CfFrrjcn9wDjr6k5KMUyjbEKagKMxfqGa2LqV2fwP3p9ZIOAIcteNnETZw+Ioe655EV9lGcOOcx5YQopPxee1NUdz1uSI8tgnJU4Yp704ay0TBtQUH+iE6MJQve/CdRyvIvKv+xFcU9s+7Lr4RmoHXtJ6DVzl1ErTKT1fFsfMkHsM0bANPMg7ZG6/XnCR8eyVLeVGLGoZPIqmga+IHEBDaC6ZYEn9/Boc+dGDVlB032diup0Edtdl3ReVFpYAh0H9vNpz3ylfVrNSe8qRgPZfst6sBWXCadZVMXTUw0lrwydwxzx9z0QVyVKqmmDv/S+7mJnemOn8EP4qdffyyXGi1qaCGXiktUEPdH7xnDGqKbRyx5c8pwjFe8mLLEJWpqMR5nvJvy81hoeEM1ZgkR/1mIQuaRsfCmm5oiq5B2kGDQjTIPyOUzv9suR6D506ddYWwcM0JlR1DnKL0C5ibGrTw4YJvSb1WK4K88GiFxIeXH1E5UgshT6D0Il1/wdhyyQ451TqjP6eHam+DK3j00F7Fv5QSMJk8ecdxuDZeOi46alQxLeLLXkJP0Fvn3N0zbAUBSD2/abX/8KCZZn1mj5VZ+Tcypd4=
  file:
    - dist/stdinserver_darwin_386
    - dist/stdinserver_darwin_amd64
    - dist/stdinserver_freebsd_386
    - dist/stdinserver_freebsd_amd64
    - dist/stdinserver_freebsd_arm
    - dist/stdinserver_linux_386
    - dist/stdinserver_linux_amd64
    - dist/stdinserver_linux_arm
    - dist/stdinserver_netbsd_386
    - dist/stdinserver_netbsd_amd64
    - dist/stdinserver_netbsd_arm
    - dist/stdinserver_openbsd_386
    - dist/stdinserver_openbsd_amd64
    - dist/stdinserver_windows_386.exe
    - dist/stdinserver_windows_amd64.exe
  skip_cleanup: true
  on:
    tags: true
